### ISSUE TITLE
Add month and year picker

### ISSUE THREAD

**Issue by wescopeland** [AmirkabirDataMiners/ADM-dateTimePicker#1]
This datepicker is great! But one thing that is missing compared to Angular UI's datepicker is the ability to, from within the control itself, explicitly select months and years.

For example, if I open a datepicker and it defaults at "January 2016", if I need to go back to "February 1990", there isn't an easy way in the datepicker itself to do that.

**Comment by MeTe-30** [comment]
Thanks Wes, glad to hear that.
Absolutely! I'll rework this issue into a feature request :+1: 
See it soon on next update.

**Comment by MeTe-30** [comment]
Added on V1.1
