### ISSUE TITLE
toDay not working ! [bug]

### ISSUE THREAD

**Issue by mrsadeghi** [AmirkabirDataMiners/ADM-dateTimePicker#10]
when i click  'ToDay' button I expect that calendar go to to day but it not reset to today.

**Comment by MeTe-30** [comment]
Are you sure?
Check this [Plunker](http://plnkr.co/edit/TYbyoGI0aseXnR3pryMx?p=preview), 
`Today` and `امروز` buttons are working well.
Can you tell me more detail?

**Comment by mrsadeghi** [comment]
yes
you can see ADMdtp live example here [demo](http://amirkabirdataminers.github.io/ADM-dateTimePicker/#/)
i click 16-02-01 
next click 'Today' or 'امروز'  and calendar days hide and showed with animation but selected date still 16-02-01.
i check in chrome browser (version 48)

**Comment by MeTe-30** [comment]
Maybe it's misunderstanding! :)
`Today` button is just a shortcut to current year and month.
most people just want to know the current day quickly, `Today` button with your meaning will ruined the selected day.
I think i need more feedback about this.
Anyway, tnx refigh

**Comment by vishnur-github** [comment]
Even I am also facing same issue. Normal perception would be to have today's date and time, if any body sees that today button. Not sure if any latest update is there on this. If this has been fixed then pls share version or if it will remain like this, then please let me know
