### ISSUE TITLE
Today button doesn't work

### ISSUE THREAD

**Issue by ata-marzban** [AmirkabirDataMiners/ADM-dateTimePicker#101]
Clicking the today button just refreshes the calendar and doesn't select the present day.

**Comment by arash-khajelou** [comment]
the today button in every calendar module, works like that :) so this is not a bug or issue :d

**Comment by ata-marzban** [comment]
Yeah you're right i noticed that later the same day.

**Comment by arash-khajelou** [comment]
so you can close the issue
