### ISSUE TITLE
Append popup div to body [SURVEY]

### ISSUE THREAD

**Issue by rkeshmir** [AmirkabirDataMiners/ADM-dateTimePicker#13]
popup div is being appended to its parent element. It makes it to be covered by small parent element. It may be an 'append to body' option which let the popup element appending to body element. This option exist in [bootstrap ui datepicker](https://angular-ui.github.io/bootstrap/).

**Comment by MeTe-30** [comment]
Hi Reza,
That makes my do lots of changes. Because second directive is nested directive and require the main directive.
So it's not that easy.
I appreciate your help, but sorry! need more request on this feature.
