### ISSUE TITLE
Sending form by clicking in a button

### ISSUE THREAD

**Issue by adrianolobo** [AmirkabirDataMiners/ADM-dateTimePicker#14]
Hey, first of all. Congratulations for the only user friendly angularjs datetimepicker that doesn't require 1 billions clicks from the user to set the date/time.

I found an issue with ADM which is when the component is inside a form and I click in the "Today" button, as the button is not set as type="Button", the form is submitted.

It looks very easy to fix but I don't know if I have enough knowledge of angularjs and git to make a pull request of this.

**Comment by MeTe-30** [comment]
Hi,
Thank you so much. glad to hear that :)

Yes! you are right!
Thanks for helping.
I'll fix that as soon as possible.
