### ISSUE TITLE
Option default - no date (= 'none')

### ISSUE THREAD

**Issue by newargus** [AmirkabirDataMiners/ADM-dateTimePicker#17]
Default is 'today', but what is the right option to have it  blank, with no value un ng-model. False seems to work, but 'none' would be better, no ?

**Comment by MeTe-30** [comment]
You mean, you set `today` value for `default` option in `app.config` but need to set `none` value for specific directive against the default option?

**Comment by newargus** [comment]
Back to my project. To Answer to tout question, yes exactly the case. I've try afterwards the opposite, It's working of course.... 

But it would be nice to have it also working with a Key Word to have the opposite behavior.
