### ISSUE TITLE
Error when not assigning fulldata with angularjs 1.5

### ISSUE THREAD

**Issue by newargus** [AmirkabirDataMiners/ADM-dateTimePicker#22]
I'm have a new issue after upgrading to Angular 1.5.

Following error:**http://errors.angularjs.org/1.5.0/$compile/nonassign?p0=undefined&p1=fullData&p2=admDtp**

when call like this: `<adm-dtp` ng-model='item.Date_Ouverture' options='{format: "DD/MM/YYYY", autoClose: `true}'">`

Error not appearing when adding full-data
`<adm-dtp` ng-model='item.Date_Ouverture' options='{format: "DD/MM/YYYY", autoClose: true}' `full-data="date_details_Ouverture">`

Did I miss something ?

**Comment by MeTe-30** [comment]
After a year!
Sorry!
I'm sure your problem is solved now!
Maybe in that time i forgot to define `fullData` as an optional attribute.
