### ISSUE TITLE
Removing jalali from template

### ISSUE THREAD

**Issue by kaldown** [AmirkabirDataMiners/ADM-dateTimePicker#23]
Is it possible to remove `jalali` from view?

**Comment by MeTe-30** [comment]
Yes, as you can see in [README](https://github.com/AmirkabirDataMiners/ADM-dateTimePicker#quick-look), set `multiple: false` to remove `Jalali` from datePicker.
```html
<adm-dtp ng-model='date' options='{multiple: false}'></adm-dtp>
```
