### ISSUE TITLE
Label issue when the first thing you do is to paste a date

### ISSUE THREAD

**Issue by lucax88x** [AmirkabirDataMiners/ADM-dateTimePicker#25]
Your demo: http://amirkabirdataminers.github.io/ADM-dateTimePicker/#/

the last field, if you try to paste a date in it's format (like 2016/04/20 00:00) AND then you open the date-picker we have the following problems:
- the correct date in the picker is not set by using the date pasted
- more important, the label is never updated when selecting the date in the datepicker

![adm-datepicker-bug](https://cloud.githubusercontent.com/assets/6294464/14426433/48846330-ffef-11e5-97a6-aafb347a531e.gif)

**Comment by MeTe-30** [comment]
You are right,
I think this problem happens only when ngModel is empty.

**Comment by lucax88x** [comment]
Nice, if I find the time, I can help you fixing it!
