### ISSUE TITLE
[Request] AM/PM Time

### ISSUE THREAD

**Issue by towicode** [AmirkabirDataMiners/ADM-dateTimePicker#27]
Is is possible to do a mode with AM/PM instead of the 24 hour clock?
If this is not something you plan on adding could you give some recommendations on how I might modify this to do this.

**Comment by MeTe-30** [comment]
I'm planning on implement AM/PM for time section, but i'm not sure about the release date of next version.
Well, you have to make plenty of changes on source code (JS, Template, SCSS), it's not so easy peasy.
I'm saving time in:
```javascript
scope.time = {
    hour: '00',
    minute: '00'
}
````
So, first you have to consider `type` in this object. And after that change `24` limit of hour in `scope.changeTimeValue` function to `12`. Then you have to track `scope.time` in source code and make appropriate changes.
Sorry, that's the best i can help.
