### ISSUE TITLE
Two icons for navigating betweens months

### ISSUE THREAD

**Issue by persnoid** [AmirkabirDataMiners/ADM-dateTimePicker#28]
Hi folks,

thank you for your great DateTimePicker for Jalali calendar, maybe the best out there!

I'm trying to integrate your ADM-DateTimePicker with ionic and angular in my App.
With that I'm facing the following issues:
- There are many icons for selecting of months or navigating to other months.

![image](https://cloud.githubusercontent.com/assets/11217412/15254523/891c72d2-1937-11e6-8397-8129d591f860.png)

Thank you for your help!

Best regards,
Reza

**Comment by MeTe-30** [comment]
Hi Reza,
Thanks for your compliment. That's my pleasure
You only have this issue with month sliding arrows?
For the rest of icons, i customized Font-Awesome icons for myself, but for these two icons i'm using '\276F' & '\276E' standard Unicode.

**Comment by persnoid** [comment]
Hi MeTe-30,

yes I have this issue with month sliding arrows.
Is there any way to get rid of this issue?

regards,
Reza

**Comment by persnoid** [comment]
Hi,

I found the problem and fix it.

There is a CSS class named arrow which had conflict with the same named class in ionic.  
I changed your arrow class to ADMarrow in css file and also JS file and with that the problem is solved.

May I do a recommendation regarding your nice AngularJs-Module:
For better usability and integration of your module in other apps, It's good practice to have your own namespace in your css file. Using general names like arrow makes it fragile and difficult to integrate the module. 

Also using css classes for html or hr without namespaces can destroy the css classes of apps, which want to integrate your module.

With minimal change you can make your module to a first class angular Js Module :-)

Best regards ,
Reza
