### ISSUE TITLE
many bugs in jalali default mode + disable pattern

### ISSUE THREAD

**Issue by YounesRahimi** [AmirkabirDataMiners/ADM-dateTimePicker#33]
when setting calType to jalali and setting disable pattern, datepicker got crazy!
ex: http://younesrahimi.github.io/ali-angular-persian-datepicker/index-main.html#/

**Comment by YounesRahimi** [comment]
It's not related to disable pattern. I recognized when a default date has been set and calType is jalali, it will got crazy.

**Comment by MeTe-30** [comment]
Dude, forking module based on MIT license doesn't mean to keep everything and just remove main authors.

> The MIT license permits reuse within proprietary software provided all copies of the licensed software include a copy of the MIT License terms and the copyright notice

You just removed all me and my own company info from module and named it "Ali Angualr dateTimePicker"?
Github is not `Irani Bazi` playground refigh.
You have 1 day to remove it or revert all copyright changes before I reporting you!

**Comment by YounesRahimi** [comment]
You won @MeTe-30! I just deleted the forked repo. 
Besides I didn't know the details of MIT license, so I'm really sorry.
