### ISSUE TITLE
Missing Dependencies

### ISSUE THREAD

**Issue by ZiyedBenAhmed** [AmirkabirDataMiners/ADM-dateTimePicker#36]
`@font-face {
  font-family: 'minifontawesome';
  src: url("../fonts/font.svg#minifontawesomeregular") format("svg");
}`

Fonts directory is not there with the package. 
Have to change the css manually to another url for the fonts. Can help with that if you want.

**Comment by MeTe-30** [comment]
That was my mistake! at that time i think browsers can read SVG fonts but that was wrong and i switched to use the SVGs manually and it's look like i forgot to remove that line.
You can safely remove it.
