### ISSUE TITLE
ATM-dateTimePicker Returns an error on Custom input template

### ISSUE THREAD

**Issue by m-kermani** [AmirkabirDataMiners/ADM-dateTimePicker#39]
I am using ADM-dateTimePicker and I here is my code to make a date picker:
```
 <adm-dtp ng-model='date5' full-data='date_details' options='{dtpType: "date&time", calType: "jalali", format: "YYYY/MM/DD-hh:mm", default: "today", multiple:false, freezeInput:true }'>
        <input type='text' ng-model='date5' dtp-input />
        <button dtp-toggle > Open calendar </button>
    </adm-dtp>
```

But, when I click on the `Open calendar` button, it returns:

> TypeError: Cannot set property 'location' of undefined

What is the problem?

**Comment by MeTe-30** [comment]
Hi Mohammad,
I test your code in this [PLUNKER](http://plnkr.co/edit/qMmeR37rbK4guCdcIYkF?p=preview).
Everything is fine!
Please provide a plunker sample of error you got.

**Comment by m-kermani** [comment]
Hello @MeTe-30 

Yes! You are right, there was a problem in my own codes.
Thank you so much for your fast reply.

Great :+1:

**Comment by MeTe-30** [comment]
mokhlesim
