### ISSUE TITLE
how set mindate for today

### ISSUE THREAD

**Issue by masoud5098** [AmirkabirDataMiners/ADM-dateTimePicker#41]
سلام و تشکر و از زحمت فوق العاده شما 
چطوره میشه تاریخ شروع رو برای همان روز تنظیم کرد این تلاش من که نتیجه ای نداشت
`<adm-dtp ng-model='event.startData' full-data="event.startData_detail"   maxdate="{{event.endData_detail.unix}}" options='{dtpType:"date" , mindate:today}'></adm-dtp>`

**Comment by MeTe-30** [comment]
Hi Masoud,
Thanks.
Currently there is not shortcut for passing `today` for min and max dates. But you can handle this in another way: 

Put this in your controller:
$scope.today = new Date(new Date().dtp_shortDate()).getTime();

Then pass it to your directive:
<adm-dtp ng-model="date" mindate="{{today}}"></adm-dtp>
