### ISSUE TITLE
today() is not working correctly

### ISSUE THREAD

**Issue by m98** [AmirkabirDataMiners/ADM-dateTimePicker#43]
There are some problems in `today()`, and I know some other people filled issues about it but here are my problems with ADM, and `today()` :
- Today button needed to have a type="button", otherwise, it is trying to submit its parent form.
- Icons are not included, I don't know if is there any dependencies for ADM?

Thank you
This date picker is nice and is working good, but there are some small problems to become better

**Comment by MeTe-30** [comment]
Hi Mohammad ,
Thanks.
I think it's fixed in `V1.1.6`.

**Comment by m98** [comment]
@MeTe-30  Thanks for your good support :+1:
