### ISSUE TITLE
leap year bug

### ISSUE THREAD

**Issue by keyvanaf** [AmirkabirDataMiners/ADM-dateTimePicker#46]
hi 
when selected after leap year for example 1396/06/06 then open the calendar without select day (close out form) day increment auto(this bug in jalali calendar mode)

**Comment by Darushkanth** [comment]
Hai.. My Technical Manager helped me to solve this issue.

This issue occurs in the post Leap Year of Gregorian Date. i.e) when you enter a persian date which is equal to leap year in Gregorian calendar(say 1984), the date increment happens for the date range of 1985/01/01 to 1985/12/31.

Solution:
In ADM-dateTimePicker.js 
function getGregorianDayOfMonth(year, month, daysPassed) {
     var leaspYearCount = howManyGregorianLeapsYearPassed(year - 1);

change it to 
     var leaspYearCount = howManyGregorianLeapsYearPassed(year);

This worked fine for me.
