### ISSUE TITLE
Add start week day support

### ISSUE THREAD

**Issue by gorgekara** [AmirkabirDataMiners/ADM-dateTimePicker#47]
Currently there is no option to set a starting week day. Think it would be an awesome feature since most calendars in Europe start with Monday instead of Sunday

**Comment by gorgekara** [comment]
I've added this feature & several others to my pull request - please check it out and merge if all is good. Thanks!

**Comment by MeTe-30** [comment]
Update to latest version.
set `gregorianStartDay` to 1
