### ISSUE TITLE
Add ng-required support 

### ISSUE THREAD

**Issue by virendra656** [AmirkabirDataMiners/ADM-dateTimePicker#49]
How can i make this field as required?

**Comment by krishbang88** [comment]
You will need to define custom input template like this

          ` <adm-dtp    ng-model="dob">
                 <input  ng-model="dob" type="text" ng-required="true" dtp-input>
                </adm-dtp>`

**Comment by MeTe-30** [comment]
Update to latest version.
`ng-required` support added
