### ISSUE TITLE
Expression 'undefined' used with directive 'admDtp' is non-assignable!

### ISSUE THREAD

**Issue by lucax88x** [AmirkabirDataMiners/ADM-dateTimePicker#5]
with a simple element like 

`<adm-dtp data-ng-model="data.Person.BirthDate"></adm-dtp>`

I have the error:

`Expression 'undefined' used with directive 'admDtp' is non-assignable!`

any idea?

**Comment by MeTe-30** [comment]
@lucax88x , I apologize to be so late to answer you.  
I faced with some other important bugs .  
tnx for helping
