### ISSUE TITLE
Popup div element should be added to document body

### ISSUE THREAD

**Issue by mrmashal** [AmirkabirDataMiners/ADM-dateTimePicker#50]
Thanks for your great datepicker. I've noticed a problem when opening the calendar popup, it can go behind some other part of the page which has a higher z-index than the container of the date picker, and there would be no way to bring it to front, since the popup element is added under the ADMdtp-container. I believe the common practice for popup div elements in web design is to add them as an immediate child of document body, so they can be properly brought to front using a z-index.

Thanks again

**Comment by persnoid** [comment]
I can confirm this issue and would be thankful for a solution!

**Comment by MeTe-30** [comment]
Actually I had some problems (I cannot remember them right now).  
But I will do my best to find a solution for next publish 👍
