### ISSUE TITLE
Ability to build with custom style

### ISSUE THREAD

**Issue by sadrzadehsina** [AmirkabirDataMiners/ADM-dateTimePicker#52]
Thanks for your awesome angular directive. It works perfect.

I have noticed there is a `ADM-dateTimePicker.scss` file which the result of it is `ADM-dateTimePicker.css` thas is used as the main `css` file of date picker. 

Do you have any plan to make it customizable in terms of look and feel? I mean there should be a way of changing `ADM-dateTimePicker.scss` and make a new build of the date picker with the new css rules.

The main reason I'm asking this, is to change date picker color pallet ( and of course other settings ) based on project user interface. It would be nice if you provide a `setting.scss` file.

**Comment by MeTe-30** [comment]
Hi Sina,
Thanks.
The purpose of pushing `ADM-dateTimePicker.scss` in repository is to let developers customise their own styles.
You can see these settings at the beginnings of code:
```
$green: #56c489;
$warmBrown: #e3d6a9;
$brown: #7e4311;
$blue: #378bd3;
$orange: #fc5f2a;
$gray: #797979;
$red: #E64949;

$mainColor: $orange;
$todayColor: $warmBrown;
$dtpContainerWidth: 20em;

$FAfont: Tahoma;
$ENfont: sans-serif;
```
You only need to install [Ruby](https://rubyinstaller.org/downloads/).
Then install these packages with gem:
- gem install sass
- gem install compass
- gem install ceaser-easing

Then compile the `ADM-dateTimePicker.scss` file with command `compass watch`.
Check [Compass Documentation](http://compass-style.org/help/) for more help.
