### ISSUE TITLE
disable past

### ISSUE THREAD

**Issue by raftx24** [AmirkabirDataMiners/ADM-dateTimePicker#55]
hi.
how can I disable last dates?
thank you for nice library

**Comment by MeTe-30** [comment]
For disabling past days you can easily set mindate.

Put this in your controller:
`$scope.today = new Date(new Date().dtp_shortDate()).getTime();` 

Then pass it to your directive:
`<adm-dtp ng-model="date" mindate="{{today}}"></adm-dtp>`
