### ISSUE TITLE
file not available ceaser-easing

### ISSUE THREAD

**Issue by hanu18** [AmirkabirDataMiners/ADM-dateTimePicker#58]
Please help me 
While using SASS file how can i resolve dependency for 
@import "compass/CSS3";
@import "ceaser-easing";
when i am running my gulp task to convert all SASS to CSS it is showing some error
Error in plugin 'sass'
Message:
    app\lib\angular-material\css\ADM-dateTimePicker.scss
Error: no mixin named box-shadow
       Backtrace:
       	app/lib/angular-material/css/ADM-dateTimePicker.scss:127
        on line 127 of app/lib/angular-material/css/ADM-dateTimePicker.scss
>>             @include box-shadow(inset 0 1px 1px rgba(black,.075));

**Comment by MeTe-30** [comment]
Install these packages first:
`gem install compass`
`gem install ceaser-easing`
