### ISSUE TITLE
بسته نشدن تقویم بعد از انتخاب تاریخ

### ISSUE THREAD

**Issue by captainhamid** [AmirkabirDataMiners/ADM-dateTimePicker#60]
سلام
بعد از باز شدن تقویم و انتخاب روز تقویم بسته نمی وشد و باید در جای دیگری از صفحه کلیک کرد.

**Comment by MeTe-30** [comment]
You need to add an [extra option](https://github.com/AmirkabirDataMiners/ADM-dateTimePicker#quick-look).
`<adm-dtp ng-model="data" options="{autoClose: true}"></adm-dtp>`
