### ISSUE TITLE
how set orientation

### ISSUE THREAD

**Issue by molikh** [AmirkabirDataMiners/ADM-dateTimePicker#62]
how can i change orientation ( open in bottom ) ?

**Comment by MeTe-30** [comment]
Based on input position I calc nearest datePicker position to input, to be sure it getting fit on screen.
If you want to set another rules, you can manually change the codes inside `scope.openCalendar` function.

**Comment by molikh** [comment]
ty for your response.
i make it possible with this changes in scope.openCalendar function 
`if (_totalSize.height > window.innerHeight) {
                            if (scope.options.hasOwnProperty('orientation') && scope.options.orientation == "bottom") {
                                _pos.top = _inputBound.height + 'px';
                            } else {
                                _pos.bottom = _inputBound.height + 'px';
                            }

                        }
                        else {
                            if (scope.options.hasOwnProperty('orientation') && scope.options.orientation == "top") {
                                _pos.bottom = _inputBound.height + 'px';
                            } else {
                                _pos.top = _inputBound.height + 'px';
                            }

                        }
                            
                        if (_totalSize.width > window.innerWidth)
                            _pos.left = (window.innerWidth - _totalSize.width - 20) + 'px';
                        else
                            _pos.left = 0;
                        `

know in can have position top and botton with:
var options = { calType: 'jalali', format: 'YYYY/MM/DD',  orientation : 'bottom' }
var options = { calType: 'jalali', format: 'YYYY/MM/DD',  orientation : 'top' }

thanks alot
