### ISSUE TITLE
Missing days / Additional days - in the Jalali calendar - Mozilla Firefox !

### ISSUE THREAD

**Issue by Ashrafik** [AmirkabirDataMiners/ADM-dateTimePicker#65]
when using the **Mozilla Firefox** browser,

every first month of **Jalali** year (**Farvaedin**) has **only 7 days**
and every last month (**Esfand**) has **more than 30 days**

**How to fix this problem?**

![1](https://cloud.githubusercontent.com/assets/10134631/21985265/04029a04-dc0f-11e6-82f6-fe12f59061a8.png)
![2](https://cloud.githubusercontent.com/assets/10134631/21985266/0406e60e-dc0f-11e6-9b89-040e754a9165.png)

**Comment by MeTe-30** [comment]
OoPs!

**Comment by Ashrafik** [comment]
thanks a lot ..

**Comment by MeTe-30** [comment]
@Ashrafik YW,
before using package, be sure its version is `1.1.10`
`npm` didn't update the packages immediately.
