### ISSUE TITLE
removeIcon dosent show up

### ISSUE THREAD

**Issue by molikh** [AmirkabirDataMiners/ADM-dateTimePicker#66]
there is svg element for remove icon but it dosent show up.
dosent show in your demo too.

**Comment by MeTe-30** [comment]
Oops!
I replaced all svgs but this!

**Comment by molikh** [comment]
maybe need to consider this too (  new version or ..)
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href

**Comment by daemon606** [comment]
replace this code: 
`<svg  viewBox="0 0 24 24" ng-if="dtpValue.formated" ng-click="destroy()"> <use stroke-width="20" href="#dtpTimes" /> </svg>`
with this one: 
`<span class="fa fa-remove removeIcon" ng-if="dtpValue.formated" ng-click="destroy()"></span>`
and change removeIcon css class from this: 
`.ADMdtpInput > .removeIcon {
  position: absolute;
  display: block;
  left: 2.1em;
  top: 0;
  z-index: 3;
  fill: #E64949;
  padding: 11px;
  cursor: pointer;
  opacity: .7;
  font-size: 1.1em;
  height: 34px;
}`
to this one: 
` .removeIcon {
  position: absolute;
  display: block;
  left: 2.1em;
  top: 0;
  z-index: 3;
  color: #E64949;
  padding: 11px;
  cursor: pointer;
  opacity: .7;
  font-size: 1.1em;
  height: 34px;
}`

That's work for me.

**Comment by molikh** [comment]
ty i fixed with svg line ( build a close icon ) ;

**Comment by MeTe-30** [comment]
Fixed
