### ISSUE TITLE
improvement  when freezeInput is true

### ISSUE THREAD

**Issue by molikh** [AmirkabirDataMiners/ADM-dateTimePicker#69]
when freezeInput is true datepicke only open up when click on the icon.
it's kind of annoying so i did small change and improve it with this solution:
i put this div exactly after input tag in html template:
`<input type="text" ng-model="dtpValue.formated" ng-focus="openCalendar()" ng-disabled="option.freezeInput || option.isDeviceTouch || disable" ng-blur="modelChanged()">`

added after :
`<div ng-click="toggleCalendar()" ng-if="option.freezeInput" style="position: absolute;left:0;right:0;top:0;bottom:0;cursor: pointer;z-index:2;outline:0"></div> `

result:
`<input type="text" ng-model="dtpValue.formated" ng-focus="openCalendar()" ng-disabled="option.freezeInput || option.isDeviceTouch || disable" ng-blur="modelChanged()"><div ng-click="toggleCalendar()" ng-if="option.freezeInput" style="position: absolute;left:0;right:0;top:0;bottom:0;cursor: pointer;z-index:2;outline:0"></div> `
so now when click on disabled input toggleCaledndar will trigger

**Comment by MeTe-30** [comment]
I replaced disabled with readonly.
Update to latest version to see the changes.
