### ISSUE TITLE
Datepicker causes a problem on the safari

### ISSUE THREAD

**Issue by nasserghiasi** [AmirkabirDataMiners/ADM-dateTimePicker#73]
Datepicker makes safari or smart tv browsers crashed. you can open ADM-dateTimePicker demo page on safari and test, it uses all CPU power.

**Comment by hamidnabati** [comment]
yes, i had the same mistake! it took me two weeks to find out what causing this problem!

**Comment by MeTe-30** [comment]
One standard Date library, with too many different Date parsing structures in different browsers!!  

- Safari   new Date('2017/2/18')  =>  Sat Feb 18 2017 00:00:00 GMT+0330 (IRST)
- Safari   new Date('2017-2-18')  =>  Invalid Date
- FireFox    new Date('2017/2/18')  =>  2017-02-17T20:30:00.000Z
- FireFox    new Date('2017-2-18')  =>  2017-02-18T00:00:00.000Z
- Chrome    new Date('2017/2/18')  =>  Sat Feb 18 2017 00:00:00 GMT+0330 (IRST)
- Chrome    new Date('2017-2-18')  =>  Sat Feb 18 2017 00:00:00 GMT+0330 (IRST)

And too many other deferents!
