### ISSUE TITLE
Popup positioning Bug when using date picker in modal

### ISSUE THREAD

**Issue by alireza-es** [AmirkabirDataMiners/ADM-dateTimePicker#76]
when i upgraded adm to the last version (1.2), a bug has been appeared.
Date picker popup has been hide under modal window.

![image](https://cloud.githubusercontent.com/assets/3083080/23201550/516fefa6-f8ef-11e6-99c0-e89968046cc9.png)

**Comment by MeTe-30** [comment]
In Option, you can set `zIndex` for popup  
Check out [#Quick-Look](https://github.com/AmirkabirDataMiners/ADM-dateTimePicker#quick-look)
