### ISSUE TITLE
Add option to change month & day names

### ISSUE THREAD

**Issue by newargus** [AmirkabirDataMiners/ADM-dateTimePicker#8]
First comment: look very nice ! good job !

I will try to use it in one of my projet, but I would like to know if you could put in option the possibility to change language:

Example: The gregorian calendar in French would be:
- gregorian: { monthsNames: ['Janvier', 'Février', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Août', 'Septembre', 'Octobre', 'Novembre', 'Décembre'],daysNames: ['Dim', 'Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam'],
  today: 'Aujourd\'hui'}

The second request would be to withdraw the possibility by option to change Calandar type.

I've found the way to do it on your code, but it would be nice to have it in future version.  

Thanks.
Olivier

**Comment by MeTe-30** [comment]
@newargus glad to hear that! :)

> I will try to use it in one of my projet, but I would like to know if you could put in option the possibility to change language:

You are right, i considered the month and day names as constant variables. but in different countries it might be changed.
I'll rework this issue into a feature request. see it soon in next update.

> The second request would be to withdraw the possibility by option to change Calandar type.

As described [HERE](https://github.com/AmirkabirDataMiners/ADM-dateTimePicker#set-options-for-entire-of-app), currently you can hide calendar type switch in entire of app by setting this option in app.run:
`ADMdtp.setOptions({
calType: 'gregorian',
multiple: false
});`

Is that what you want?

**Comment by newargus** [comment]
Thanks. Yes, I went through your readme file without seeing this option, m'y mistake. (It work as expected! Maybe could have a little css enhancement to have today to the right).

By the way, it would be nice to have the demo site with your package. Because, i've try to understand how you have made your customized green date button without succes.

**Comment by MeTe-30** [comment]
> By the way, it would be nice to have the demo site with your package.

Yes, absolutely. I'm working on it. :+1: 

But before that its the code you tried for:
```html
<adm-dtp ng-model="date16" options='{format: "Date: YYYY-MM-DD  Time: (hh:mm)", default: "today"}'>
    <button class="btn btn-success btn-block" dtp-toggle >{{date16}}</button>
</adm-dtp>
```
